FROM ubuntu:18.04

LABEL maintainer="Quang Nguyen <nvq247@gmail.com>"
# 7.4.288/7.8.279.23/7.9.317.33/8.1.184
# Update & install essentials
RUN apt-get update && apt-get install -y --no-install-recommends \
    mariadb-client \
    git \
    build-essential \
    curl \
    python \
    libglib2.0-dev \
    patchelf 
    RUN cd /tmp &&  apt-get install -y ca-certificates \
    && git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git  --progress --verbose \
    && export PATH="$PATH:/tmp/depot_tools" \
    && fetch v8 \
    && cd v8 \
    && git checkout 7.5.288.31  \
    && gclient sync \
    && tools/dev/v8gen.py -vv x64.release -- \
    binutils_path=\"/usr/bin\" \
    target_os=\"linux\" \
    target_cpu=\"x64\" \
    v8_target_cpu=\"x64\" \
    v8_use_external_startup_data=false \
    is_official_build=true \
    is_component_build=true \
    is_cfi=false \
    is_clang=false \
    use_custom_libcxx=false \
    use_sysroot=false \
    use_gold=false \
    use_allocator_shim=false \
    treat_warnings_as_errors=false \
    symbol_level=0 \
    && ninja -C out.gn/x64.release/ \
    && mkdir -p /opt/libv8/lib \
    && mkdir /opt/libv8/include \
    && cp out.gn/x64.release/lib*.so out.gn/x64.release/icudtl.dat \
    /opt/libv8/lib/ \
    && cp -R include/* /opt/libv8/include/ \
    && for A in /opt/libv8/lib/*.so; do patchelf --set-rpath '$ORIGIN' $A;done \
    && rm -rf /tmp/* \

COPY ./v8js /tmp/v8js



ENV TZ=Europe/Minsk
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt -y install software-properties-common
RUN add-apt-repository ppa:ondrej/php -y
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y  php7.4 php7.4-dev

COPY ./v8js /tmp/v8js
RUN  cd /tmp/v8js \
#RUN git clone https://github.com/derrekbertrand/v8js.git \
#    && cd v8js && pwd \  
#    && git checkout test \
    && phpize \
    && ./configure LDFLAGS="-lstdc++"   --with-v8js=/opt/libv8 \
    && export NO_INTERACTION=1 \
    && make \
 	&& make test || echo 3\
    && make install 
    
